### ISSUE TITLE
Some errors Seems about `filepath` on Windows10.

### ISSUE THREAD

**Issue by scillidan** [lakuapik/gh-inspire#4]
Seems some errors about `filepath` on Windows10.

```cmd
D:\home  λ gh inspire   
jq: error: Could not open file C:\Users\scillidan\AppData\Local\GitHub: No such file or directory
jq: error: Could not open file CLI\extensions\gh-inspire\gh-inspire/quotes.min.json: No such file or directory
shuf: invalid input range: ‘’
```

Only `GitHub CLI` in `AppData/local`,
and `quotes.min.json` is here:
`C:\Users\scillidan\AppData\Local\GitHub CLI\extensions\gh-inspire\quotes.min.json`

**Comment by lakuapik** [comment]
@scillidan thank you for reporting this, unfornately i dont have windows to try it. a PR is welcome.

**Comment by scillidan** [comment]
@lakuapik OK, I'll give it a try. Because I'm inexperienced🤡.

**Comment by scillidan** [comment]
Seems to be because there is a space in the path, between `github cli`.
I don't know if it works, but I try change the line https://github.com/lakuapik/gh-inspire/blob/b427d37ae20838bfaea921870f5a88db9004e428/gh-inspire#L9

to:

```
    if ! type -p "$1 >/dev/null"; then
```

But said:

```cmd
D:\home  λ where fold
C:\Users\scillidan\scoop\apps\git\current\usr\bin\fold.exe
C:\Users\scillidan\scoop\shims\fold.exe

D:\home  λ gh inspire2          

ERROR: fold not found on the system
please install and try again
```

**Comment by scillidan** [comment]
I get `gh.exe` from [releases](https://github.com/cli/cli/releases). And used extension of `gh` from source. Then I found that `gh-inspire` works well on Windows 10.

The `shuf`, `fold`, `bash.exe` be installed with install Git:

```
scoop install git jq
```

```
git clone https://github.com/lakuapik/gh-inspire
cd gh-inspire
```

Write the right path of `quotes.min.json` at https://github.com/lakuapik/gh-inspire/blob/b427d37ae20838bfaea921870f5a88db9004e428/gh-inspire#L20C1-L20C41

```
bash.exe gh-inspire
```

Example return:

```
DRY - Don't Repeat Yourself - Every piece of knowledge must have a single, 
unambiguous, athoritative representation within a system.

~ Andy Hunt & Dave Thomas
```
